name: devsecops proj

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        pip install kafka-python redis pymongo

    - name: Run Basic Import Test
      run: |
        python -c "import kafka, redis, pymongo; print('All imports OK')"
